# Generated by terraform/envs/testnet-1 (outputs.tf) — do not hand edit.
# Usage:  ssh -F ansible/inventories/testnet-1/ssh_config testnet-1-gcp-validator-v6
# Ansible uses it through ansible_ssh_common_args in hosts.yml.
#
# Every host except the bastions is reached on its private IP by
# ProxyJump-ing through a bastion. Which bastion is decided by
# var.bastion_ssh_entry (per-cloud by default: each cloud's own).

%{ for name, b in bastions ~}
%{ if b.ssh_entry ~}
Host ${b.hostname} ${b.public_ipv4}
  HostName ${b.public_ipv4}

%{ else ~}
Host ${b.hostname} ${b.private_ip}
  HostName ${b.private_ip}
  ProxyJump ${jump_for[b.cloud]}

%{ endif ~}
%{ endfor ~}
%{ for name, h in jumped_hosts ~}
Host ${h.hostname} ${h.private_ip}
  HostName ${h.private_ip}
  ProxyJump ${jump_for[h.cloud]}

%{ endfor ~}
Host *
  User ${ssh_user}
  IdentitiesOnly yes
  ForwardAgent no
  # First connection to a freshly provisioned host is trust-on-first-use;
  # a CHANGED key afterwards is still refused (that is the case that matters).
  StrictHostKeyChecking accept-new
  ServerAliveInterval 30
