# Generated by terraform/envs/devnet-1 (outputs.tf) — do not hand edit.
# Usage:  ssh -F ansible/inventories/devnet-1/ssh_config devnet-1-hetzner-validator-v1
# Ansible uses it through ansible_ssh_common_args in hosts.yml.
#
# Every host except the bastion is reached on its private IP by
# ProxyJump-ing through the one bastion.

Host ${bastion.hostname} ${bastion.public_ipv4}
  HostName ${bastion.public_ipv4}

%{ for name, h in jumped_hosts ~}
Host ${h.hostname} ${h.private_ip}
  HostName ${h.private_ip}
  ProxyJump ${bastion.hostname}

%{ endfor ~}
Host *
  User ${ssh_user}
  IdentitiesOnly yes
  ForwardAgent no
  # First connection to a freshly provisioned host is trust-on-first-use;
  # a CHANGED key afterwards is still refused (that is the case that matters).
  StrictHostKeyChecking accept-new
  ServerAliveInterval 30
